[tools]
antigravity-cli = "latest"
"aqua:dduan/tre" = "latest"
"aqua:fish-shell/fish-shell" = "latest"
bat = "latest"
chezmoi = "latest"
claude-code = "latest"
codex = "latest"
copilot = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
"github:knqyf263/pet" = "latest"
grok = { version = "latest", bin = "grok", platforms = { windows-arm64 = { bin = "grok.exe", url = "https://storage.googleapis.com/grok-build-public-artifacts/cli/grok-{{ version }}-windows-aarch64.exe" }, windows-x64 = { bin = "grok.exe", url = "https://storage.googleapis.com/grok-build-public-artifacts/cli/grok-{{ version }}-windows-x86_64.exe" } }, url = 'https://storage.googleapis.com/grok-build-public-artifacts/cli/grok-{{ version }}-{{ os() }}-{{ arch(x64="x86_64", arm64="aarch64") }}', version_list_url = "https://x.ai/cli/stable" }
herdr = "latest"
neovim = "latest"
node = "latest"
ripgrep = "latest"
usage = "latest"
yazi = "latest"
