[tools]
antigravity-cli = "latest"
"aqua:dduan/tre" = "latest"
"aqua:fish-shell/fish-shell" = "latest"
bat = "latest"
chezmoi = "latest"
claude-code = "latest"
codex = "latest"
copilot = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
"github:knqyf263/pet" = "latest"
herdr = "latest"
neovim = "latest"
node = "latest"
ripgrep = "latest"
usage = "latest"
yazi = "latest"

[settings]

[settings.ruby]
compile = false
